# Generated by Django 4.0.5 on 2022-06-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='desription',
        ),
    ]
